
package com.bancodebogota.customers.product.service.v2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-24T11:00:08.002-05:00
 * Generated source version: 3.5.1
 */

@WebFault(name = "setSendOtpFault", targetNamespace = "urn://bancodebogota.com/customers/product/service/v2/")
public class SetSendOtpFault_Exception extends Exception {

    private com.bancodebogota.customers.product.service.v2.SetSendOtpFault faultInfo;

    public SetSendOtpFault_Exception() {
        super();
    }

    public SetSendOtpFault_Exception(String message) {
        super(message);
    }

    public SetSendOtpFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SetSendOtpFault_Exception(String message, com.bancodebogota.customers.product.service.v2.SetSendOtpFault setSendOtpFault) {
        super(message);
        this.faultInfo = setSendOtpFault;
    }

    public SetSendOtpFault_Exception(String message, com.bancodebogota.customers.product.service.v2.SetSendOtpFault setSendOtpFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = setSendOtpFault;
    }

    public com.bancodebogota.customers.product.service.v2.SetSendOtpFault getFaultInfo() {
        return this.faultInfo;
    }
}
