package com.bancodebogota.customers.product.service.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-24T11:00:08.043-05:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "urn://bancodebogota.com/customers/product/service/v2/", name = "TokenInquiryManagementV2")
@XmlSeeAlso({com.bancodebogota.customers.product.v1.ObjectFactory.class, com.bancodebogota.customers.token.event.ObjectFactory.class, ObjectFactory.class, com.bancodebogota.ifx.base.v1.ObjectFactory.class, com.bancodebogota.customers.involvedparty.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TokenInquiryManagementV2 {

    @WebMethod(action = "urn://bancodebogota.com/customers/product/service/v2/setSendOtp")
    @WebResult(name = "setSendOtpResponse", targetNamespace = "urn://bancodebogota.com/customers/product/service/v2/", partName = "SendOtpAddRs")
    public SetSendOtpResponse setSendOtp(

        @WebParam(partName = "SendOtpAddRq", name = "setSendOtpRequest", targetNamespace = "urn://bancodebogota.com/customers/product/service/v2/")
        SetSendOtpRequest sendOtpAddRq
    ) throws SetSendOtpFault_Exception;

    @WebMethod(action = "urn://bancodebogota.com/customers/product/service/v2/getTokenValidation")
    @WebResult(name = "getTokenValidationResponse", targetNamespace = "urn://bancodebogota.com/customers/product/service/v2/", partName = "TokenValInqRs")
    public GetTokenValidationResponse getTokenValidation(

        @WebParam(partName = "TokenValInqRq", name = "getTokenValidationRequest", targetNamespace = "urn://bancodebogota.com/customers/product/service/v2/")
        GetTokenValidationRequest tokenValInqRq
    ) throws GetTokenValidationFault_Exception;

    @WebMethod(action = "urn://bancodebogota.com/customers/product/service/v2/getTokenInfo")
    @WebResult(name = "getTokenInfoResponse", targetNamespace = "urn://bancodebogota.com/customers/product/service/v2/", partName = "TokenInfoInqRs")
    public GetTokenInfoResponse getTokenInfo(

        @WebParam(partName = "TokenInfoInqRq", name = "getTokenInfoRequest", targetNamespace = "urn://bancodebogota.com/customers/product/service/v2/")
        GetTokenInfoRequest tokenInfoInqRq
    ) throws GetTokenInfoFault_Exception;
}
